apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "ci-cd-next-project.fullname" . } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels: { { - include "ci-cd-next-project.name" . | nindent 6 } }
  template:
    metadata:
      labels:
        app: { { include "ci-cd-next-project.name" . | nindent 4 } }
    spec:
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: { { .Values.service.targetPort | default 3000 } }
              protocol: TCP
